import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
import * as core from '../src/shared-admin-core.js';
import {createAdminSync} from '../src/shared-admin-sync.js';
const settle=async()=>{for(let i=0;i<40;i++) await Promise.resolve();};
const date='2099-01-04';
const snapshot=()=>({ok:true,planDate:date,writeMode:'shared',draftRevision:3,eventCursor:19,publishedRevision:0,baselinePublishedRevision:0,settingsVersion:1,drivers:[{slug:'a',displayName:'Synthetic'}],riders:[{id:'00000000-0000-4000-8000-000000000002',name:'Synthetic rider',address:'Example',driverSlug:'a',entityVersion:2,stopOrder:1}],groupVersions:{a:3},publishedSnapshot:{ok:true,plan:{date},stops:[],drivers:[],people:[]}});
async function appHarness(handler=()=>undefined){
 const elements=new Map(),storage=new Map(),calls=[],listeners={};let seq=10;
 const element=()=>({innerHTML:'',textContent:'',value:'',dataset:{},hidden:false,classList:{add(){},remove(){},contains(){return false;},toggle(){}},setAttribute(){},addEventListener(){},querySelector(){return element();},focus(){}});
 const get=q=>{if(!elements.has(q))elements.set(q,element());return elements.get(q);};
 const document={hidden:false,activeElement:null,querySelector:get,querySelectorAll:()=>[],addEventListener:(name,fn)=>listeners[name]=fn,removeEventListener(){}};
 const context={console:{...console,error(){},warn(){}},URLSearchParams,encodeURIComponent,crypto:{randomUUID:()=>`00000000-0000-4000-8000-${String(++seq).padStart(12,'0')}`},setTimeout:()=>1,clearTimeout(){},AbortController,
  FormData:class{constructor(form){this.values=form?.values||{};}get(key){return this.values[key];}entries(){return Object.entries(this.values)[Symbol.iterator]();}},
  location:{href:'https://example.test/',search:''},navigator:{onLine:true},document,
  window:{isSecureContext:false,RideShared:{...core,createAdminSync:options=>createAdminSync({...options,clock:{setTimeout:()=>1,clearTimeout(){}}})},addEventListener:(name,fn)=>listeners[name]=fn,removeEventListener(){}},
  localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},
  fetch:async(url,init)=>{const name=url.split('/').at(-1),args=JSON.parse(init?.body||'{}');if(!name.startsWith('ride_admin_'))return {ok:true,json:async()=>[]};calls.push({name,args});const custom=await handler(name,args);const result=custom ?? (name==='ride_admin_shared_context'?{...snapshot(),actorKey:'profile:a',initialized:true}:name==='ride_admin_shared_snapshot'?snapshot():name==='ride_admin_shared_secondary'?{ok:true,actorKey:'profile:a',planDate:date,people:[],driverPool:[],brandingVersion:1,branding:{}}:name==='ride_admin_shared_operation'?{ok:false,code:'not_found'}:{ok:true});return {ok:true,json:async()=>result};}};
 vm.createContext(context);const html=await readFile(new URL('../index.html',import.meta.url),'utf8');const script=html.match(/<script>([\s\S]*)<\/script>/)[1];
 vm.runInContext(script+`\nglobalThis.app={state,loadAdminSnapshot,signOutAdmin,saveAdminDraftFromForm,deleteAdminDraftStop,publishAdminDraft,runAdminSharedSecondary,adminEditView,render,applyAdminSharedState:typeof applyAdminSharedState==='function'?applyAdminSharedState:undefined,reviewAdminShared:typeof reviewAdminShared==='function'?reviewAdminShared:undefined,retryAdminSharedPending:typeof retryAdminSharedPending==='function'?retryAdminSharedPending:undefined};`,context);
 const app=context.app;app.state.planDate=date;return {app,calls,elements,storage,context,async start(){await app.loadAdminSnapshot('synthetic-token');await settle();}};
}
test('shared login hydrates protected snapshot/secondary and never selects legacy recovery winner',async()=>{const h=await appHarness();await h.start();assert.equal(h.app.state.adminShared?.actorKey,'profile:a');assert.equal(h.app.state.adminDraftStops[0].name,'Synthetic rider');assert.equal(h.calls.some(c=>c.name==='ride_admin_get_draft'),false);h.app.signOutAdmin();});
test('form_focus_preserved and captured versions survive remote snapshot; only safe route region changes',async()=>{const h=await appHarness();await h.start();assert.equal(typeof h.app.applyAdminSharedState,'function');const c=h.app.state.adminShared;h.app.state.view='adminEdit';const input={value:'private typed text',selectionStart:5};h.context.document.activeElement=input;const form=h.elements.get('#screen');form.innerHTML='existing form';const old=c.snapshot;h.app.applyAdminSharedState(c,{status:'saved',snapshot:{...old,draftRevision:4,riders:[{...old.riders[0],name:'Remote'}]}});assert.equal(form.innerHTML,'existing form');assert.equal(input.value,'private typed text');assert.equal(input.selectionStart,5);assert.equal(h.app.state.adminDraftStops[0].name,'Remote');h.app.signOutAdmin();});
test('shared rider save uses captured versions, records uncertainty, reconciles not_found, retries same body/id',async()=>{let writes=0;const h=await appHarness(name=>{if(name==='ride_admin_shared_mutate'){writes++;throw Error('lost reply');}});await h.start();const c=h.app.state.adminShared;const form={dataset:{sharedSnapshot:JSON.stringify(c.snapshot)},values:{...c.snapshot.riders[0],name:'Personal'}};await h.app.saveAdminDraftFromForm(form);await settle();assert.equal(writes,1);const pending=c.pendingOperation;assert.ok(pending?.operationId);assert.equal(pending.args.p_operation.expectedEntityVersion,2);await h.app.saveAdminDraftFromForm(form);assert.equal(writes,1);assert.equal(typeof h.app.retryAdminSharedPending,'function');await h.app.retryAdminSharedPending();await settle();assert.equal(writes,2);const bodies=h.calls.filter(c=>c.name==='ride_admin_shared_mutate').map(c=>c.args.p_operation);assert.deepEqual(bodies[0],bodies[1]);assert.ok(c.pendingOperation);assert.equal(h.calls.some(c=>c.name==='ride_admin_save_draft'),false);assert.equal([...h.storage.values()].some(v=>v.includes('synthetic-token')),false);h.app.signOutAdmin();});
test('publish requires current online review and captures mandatory revisions',async()=>{const h=await appHarness();await h.start();await h.app.publishAdminDraft();assert.equal(h.calls.some(c=>c.name==='ride_admin_shared_publish'),false);assert.equal(typeof h.app.reviewAdminShared,'function');await h.app.reviewAdminShared();await h.app.publishAdminDraft();const call=h.calls.find(c=>c.name==='ride_admin_shared_publish');assert.ok(call);assert.equal(call.args.p_expected_draft_revision,3);assert.equal(call.args.p_expected_baseline_revision,0);h.app.signOutAdmin();});
test('signout clears private state immediately and delayed login cannot resurrect it',async()=>{let resolve;const wait=new Promise(r=>resolve=r);const h=await appHarness(name=>name==='ride_admin_shared_context'?wait:undefined);const opening=h.app.loadAdminSnapshot('synthetic-token');await settle();await h.app.signOutAdmin();resolve({...snapshot(),actorKey:'profile:a',initialized:true});await opening;assert.equal(h.app.state.admin,null);assert.equal(h.app.state.adminShared,null);assert.equal(h.app.state.adminDraftStops.length,0);});
test('secondary old response cannot roll back newer person projection and invalid auth locks private UI',async()=>{let resolve;const wait=new Promise(r=>resolve=r);const h=await appHarness(name=>name==='ride_admin_shared_save_person'?wait:undefined);await h.start();const c=h.app.state.adminShared;h.app.state.admin.people=[{id:'p',name:'initial',recordVersion:1}];const saving=h.app.runAdminSharedSecondary('person',{id:'p',name:'saved'},{recordVersion:1});h.app.state.admin.people=[{id:'p',name:'newest',recordVersion:3}];resolve({ok:true,value:{person:{id:'p',name:'old reply',recordVersion:2}}});await saving;assert.equal(h.app.state.admin.people[0].name,'newest');h.app.applyAdminSharedState(c,{status:'locked',snapshot:null});assert.equal(h.app.state.admin,null);assert.equal(h.app.state.adminShared,null);assert.equal(h.app.state.adminPersonDraft,null);});
test('shared login keeps protected security and destination, clears prior actor forms',async()=>{const h=await appHarness(name=>name==='ride_admin_shared_snapshot'?{...snapshot(),publishedSnapshot:{...snapshot().publishedSnapshot,security:{actor:{type:'profile',label:'Synthetic Alpha'}},destination:{label:'Synthetic destination'}}}:undefined);h.app.state.adminMergeDraft={private:'old actor'};h.app.state.adminAiResult={private:'old actor'};await h.start();assert.equal(h.app.state.admin?.security?.actor?.label,'Synthetic Alpha');assert.equal(h.app.state.destination?.label,'Synthetic destination');await h.app.signOutAdmin();assert.equal(h.app.state.adminMergeDraft,null);assert.equal(h.app.state.adminAiResult,null);});
test('lost publish response retains original versioned request and blocks another publish',async()=>{let writes=0;const h=await appHarness(name=>{if(name==='ride_admin_shared_publish'){writes++;throw Error('timeout');}});await h.start();await h.app.reviewAdminShared();await h.app.publishAdminDraft();await settle();const pending=h.app.state.adminShared.pendingOperation;assert.equal(pending.kind,'publish');assert.equal(pending.args.p_expected_draft_revision,3);await h.app.publishAdminDraft();assert.equal(writes,1);await h.app.signOutAdmin();});
test('catalog uncertainty recovery never persists driver passcodes or admin tokens',async()=>{const h=await appHarness(name=>{if(name==='ride_admin_shared_add_driver')throw Error('timeout');});await h.start();await h.app.runAdminSharedSecondary('catalog',{name:'Synthetic',passcode:'private-driver-secret'});await settle();assert.equal([...h.storage.values()].some(v=>v.includes('private-driver-secret')||v.includes('synthetic-token')),false);await h.app.signOutAdmin();});
test('secondary success clears saved personal dirty state; offline and remote revisions invalidate review',async()=>{const h=await appHarness();await h.start();const c=h.app.state.adminShared;c.personalDirty=true;await h.app.runAdminSharedSecondary('route',{planTitle:'Synthetic'},{recordVersion:1});assert.equal(c.personalDirty,false);await h.app.reviewAdminShared();h.context.navigator.onLine=false;await h.app.publishAdminDraft();assert.equal(h.calls.some(c=>c.name==='ride_admin_shared_publish'),false);h.context.navigator.onLine=true;h.app.applyAdminSharedState(c,{status:'saved',snapshot:{...c.snapshot,draftRevision:4,eventCursor:31}});assert.equal(c.review,null);await h.app.signOutAdmin();});
test('same actor sign-in retains uncertain operation identity without auto-replaying',async()=>{const h=await appHarness(name=>{if(name==='ride_admin_shared_mutate')throw Error('timeout');});await h.start();const c=h.app.state.adminShared;const form={dataset:{sharedSnapshot:JSON.stringify(c.snapshot)},values:{...c.snapshot.riders[0],name:'Personal'}};await h.app.saveAdminDraftFromForm(form);await settle();const id=c.pendingOperation.operationId;await h.app.signOutAdmin();await h.start();assert.equal(h.app.state.adminShared.pendingOperation?.operationId,id);assert.equal(h.calls.filter(c=>c.name==='ride_admin_shared_mutate').length,1);await h.app.signOutAdmin();});
test('account switch clears old private projections before authentication and on rejection',async()=>{let reject=false;const h=await appHarness(name=>reject && name==='ride_admin_shared_context'?{ok:false,code:'invalid_admin_code'}:undefined);await h.start();h.app.state.adminPersonDraft={name:'old private form'};reject=true;await h.app.loadAdminSnapshot('other-token');assert.equal(h.app.state.admin,null);assert.equal(h.app.state.adminPersonDraft,null);assert.equal(h.app.state.adminDraftStops.length,0);await h.app.signOutAdmin();});
test('shared form data uses the draft capture and survives typing during a pending successful save',async()=>{let resolve;const reply=new Promise(r=>resolve=r);const h=await appHarness(name=>name==='ride_admin_shared_mutate'?reply:undefined);await h.start();const c=h.app.state.adminShared;h.app.state.view='adminEdit';const form={dataset:{sharedSnapshot:JSON.stringify(c.snapshot)},values:{...c.snapshot.riders[0],name:'Saved version'}};const saving=h.app.saveAdminDraftFromForm(form);c.editVersion=1;c.personalDirty=true;resolve({ok:true});await saving;assert.equal(h.app.state.view,'adminEdit');assert.equal(c.personalDirty,true);await h.app.signOutAdmin();});
test('secondary refresh is serialized with metadata polling and does not overlap focus refresh',async()=>{let hold=false,release,contexts=0;const wait=new Promise(r=>release=r);const h=await appHarness(name=>{if(name==='ride_admin_shared_context')contexts++;if(hold && name==='ride_admin_shared_secondary')return wait;});await h.start();h.app.state.adminActiveTab='people';hold=true;const first=h.app.state.adminShared.sync.refresh('poll');await settle();const count=contexts;const next=h.app.state.adminShared.sync.refresh('focus');await settle();assert.equal(contexts,count);release({ok:true,actorKey:'profile:a',planDate:date,people:[],driverPool:[],brandingVersion:1,branding:{}});await first;await next;await h.app.signOutAdmin();});
test('delayed logout response cannot clear a newly signed-in workspace',async()=>{let release;const wait=new Promise(r=>release=r);const h=await appHarness();await h.start();h.app.state.adminSession={access_token:'old-session'};const priorFetch=h.context.fetch;h.context.fetch=(url,init)=>url.includes('/auth/v1/logout')?wait:priorFetch(url,init);const logout=h.app.signOutAdmin();await h.start();const current=h.app.state.adminShared;release({ok:true,json:async()=>({})});await logout;assert.ok(h.app.state.admin);assert.equal(h.app.state.adminShared,current);await h.app.signOutAdmin();});
